let attrs = [

    { "name": "ACOG Sight", "img": "test", "id": 0 },
    { "name": "Adjustable Stock", "img": "test", "id": 1 },
    { "name": "Ballistics CPU", "img": "test", "id": 2 },
    { "name": "Dual Band Scope", "img": "test", "id": 3 },
    { "name": "Dual Wield", "img": "test", "id": 4 },
    { "name": "EOTech Sight", "img": "test", "id": 5 },
    { "name": "Extended Clip", "img": "test", "id": 6 },
    { "name": "Fast Mag", "img": "test", "id": 7 },
    { "name": "Full Metal Jacket", "img": "test", "id": 8 },
    { "name": "Fore Grip", "img": "test", "id": 9 },
    { "name": "Grenade Launcher", "img": "test", "id": 10 },
    { "name": "Hybrid Optic", "img": "test", "id": 11 },
    { "name": "Laser Sight", "img": "test", "id": 12 },
    { "name": "Long Barrel", "img": "test", "id": 13 },
    { "name": "Millimeter Scanner", "img": "test", "id": 14 },
    { "name": "Quickdraw Handle", "img": "test", "id": 15 },
    { "name": "Rapid Fire", "img": "test", "id": 16 },
    { "name": "Reflex Sight", "img": "test", "id": 17 },
    { "name": "Select Fire", "img": "test", "id": 18 },
    { "name": "Suppressor", "img": "test", "id": 19 },
    { "name": "Tactical Knife", "img": "test", "id": 20 },
    { "name": "Target Finder", "img": "test", "id": 20 },
    { "name": "Tri-Bolt", "img": "test", "id": 21 },
    { "name": "Variable Zoom", "img": "test", "id": 22 },
    { "name": "Iron Sight", "img": "test", "id": 24 },

]