let attrs = [

    "ACOG Sight",
    "Adjustable Stock",
    "Ballistics CPU",
    "Dual Band Scope",
    "Dual Wield",
    "EOTech Sight",
    "Extended Clip",
    "Fast Mag",
    "Full Metal Jacket",
    "Fore Grip",
    "Grenade Launcher",
    "Hybrid Optic",
    "Laser Sight",
    "Long Barrel",
    "Millimeter Scanner",
    "Quickdraw Handle",
    "Rapid Fire",
    "Reflex Sight",
    "Select Fire",
    "Suppressor",
    "Tactical Knife",
    "Target Finder",
    "Tri-Bolt",
    "Variable Zoom",
]